# MAN4HEALTH
# 2021/2022/2023
# 

openapi: 3.0.0

# General Data Model Information
info:
  title: MAN4HEALTH Project
  description: Data model for the MAN4HEALTH project
  version: 0.0.1
  contact:
    name: New management strategies in olive groves for improving soil health and crop yield
    url: https://man4health.ipb.pt/
  
components:
  schemas: 
    Terrain: 
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/Terrain/model.yaml#/Terrain"
    Parcel:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/Parcel/model.yaml#/Parcel"
    Device:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/Device/model.yaml#/Device"
    Moisture:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/Sensors/Moisture/model.yaml#/moisture"
    Temperature:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/Sensors/Temperature/model.yaml#/temperature"
    Battery:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/Sensors/Moisture/model.yaml#/battery"
    LoRa:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/Hardware/Transceiver/LoRa/model.yaml#/lora"      

paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        '200':
          description: 'OK'
          content:
            application/ld+json:
              schema:
                type: object
