# MAN4HEALTH
# 2021/2022/2023
# 

openapi: 3.0.0

# General Data Model Information
info:
  title: MAN4HEALTH Project
  description: Data model for the MAN4HEALTH project
  version: 0.0.1
  contact:
    name: New management strategies in olive groves for improving soil health and crop yield
    url: https://man4health.ipb.pt/
  
components:
  schemas: 
    Basestation: 
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/YAML/basestation.yaml#/basestation"
    Gateway:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/YAML/gateway.yaml#/gateway"
    Supplybox:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/YAML/supplybox.yaml#/supplybox"
    Node:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/main/DataModel/YAML/node.yaml#/node"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Device
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Device/Device/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Device/Device/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
