# MAN4HEALTH
# 2021/2022/2023
# 

openapi: 3.0.0

# General Data Model Information
info:
  title: MAN4HEALTH Project
  description: Data model for the MAN4HEALTH project
  version: 0.0.1
  contact:
    name: New management strategies in olive groves for improving soil health and crop yield
    url: https://man4health.ipb.pt/
  
components:
  schemas: 
    Basestation: 
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/DataModel.yaml/basestation.yaml#/organization"
    Gateway:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/DataModel.yaml/gateway.yaml#/gateway"
    Supplybox:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/DataModel.yaml/supplybox.yaml#/supplybox"
    Node:
      $ref: "https://raw.githubusercontent.com/jpcoelhoATipbDOTpt/MAN4HEALTH/DataModel.yaml/node.yaml#/node"

paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        '200':
          description: 'OK'
          content:
            application/ld+json:
              schema:
                type: object
